### ISSUE TITLE
npm run codecept:demo:app fails with codecept.runBootstrap is not a function

### ISSUE THREAD

**Issue by pablopaul** [codecept-js/create-codeceptjs#6]
Running `npm run codecept:demo:app` fails with

```
> testcreatecodeceptjs@1.0.0 codecept:demo:app /Users/paul/projects/testcreatecodeceptjs
> codecept-ui --app  -c node_modules/@codeceptjs/examples

/Users/paul/projects/testcreatecodeceptjs/node_modules/@codeceptjs/ui/lib/model/codeceptjs-factory.js:92
    codecept.runBootstrap(() => {
             ^

TypeError: codecept.runBootstrap is not a function
    at CodeceptjsFactory.create (/Users/paul/projects/testcreatecodeceptjs/node_modules/@codeceptjs/ui/lib/model/codeceptjs-factory.js:92:14)
    at module.exports (/Users/paul/projects/testcreatecodeceptjs/node_modules/@codeceptjs/ui/lib/commands/init.js:48:21)
    at Object.<anonymous> (/Users/paul/projects/testcreatecodeceptjs/node_modules/@codeceptjs/ui/bin/codecept-ui.js:5:48)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

**Comment by DavertMik** [comment]
ok, looks like I didn't publish my latest changes to codecept-ui

**Comment by mihaigabriel16** [comment]
I'm late but has there been any updates on this? Ticket open and I just stumbled upon the issue in my project but have no idea how to fix it.
